### ISSUE TITLE
streams time series set_id command documentation is unclear

### ISSUE THREAD

**Issue by schaefer01** [coleifer/walrus#103]
Help please.
The example in https://walrus.readthedocs.io/en/latest/streams.html has:
  ts.set_id('$') # Do not read the dummy items.

I am curious about this. I go to the API, https://walrus.readthedocs.io/en/latest/api.html, and see this:
Set the maximum message id for the stream.

What is the '$' operator? what happens if I use an ID greater than the max id?
Does '$' have anything to do with reading the dummy items?
thanks,
  bob s.

Nevermind, I found an explanation with the read() command above the set_id() command. 
New question: does the ID have to be a string? Does it have to be a datetime object?

**Comment by coleifer** [comment]
It can be a `datetime` if you are using the `walrus.streams.TimeSeries` class. Otherwise it corresponds to whatever IDs you are using for your stream (or the auto-generated IDs used by Redis, which are based on timestamps).

I'd suggest that you read the redis streams documentation rather than the walrus documentation, in order to get a better understanding of how to use streams. They are by far much much more complicated than any of the other redis data-types.
