### ISSUE TITLE
Support for `IN` query

### ISSUE THREAD

**Issue by coleifer** [coleifer/walrus#11]
It would be cool to add support for `IN` queries on subclasses of `ContainerField` that support it. For instance,

```python
walrus = Walrus()

class Entry(Model):
    database = walrus
    namespace = 'myapp'
    title = TextField(index=True)
    content = TextField(
        fts=True,
        stemmer=True,
        metaphone=True)
    tags = SetField(index=True)  # "index"
```

Currently you cannot add an index to a container field, nor do these fields support any operations. It makes sense, though, to support something like:

```python
Entry.query(Entry.tags.contains('python'))
```

**Comment by coleifer** [comment]
This isn't super straightforward...I'm assuming I'd take each value in the set and re-map it into a number of other sets containing primary keys, e.g.

```
blog1.tags = {'foo', 'bar'}
blog2.tags = {'bar', 'nugget'}

Blog.tags.bar = {blog1.id, blog2.id}
Blog.tags.foo = {blog1.id}
Blog.tags.nugget = {blog2.id}
```

Changes made to the values in container fields occur separately from other changes to the model, since the containers are really just "low level" ways to access rich data types. So when updating a blog's tags, it's not immediately clear where to put the code to update the secondary indexes.

**Comment by borg286** [comment]
You already create multiple keys for each unique value observed for a full text search: https://github.com/coleifer/walrus/blob/master/walrus/models.py#L544
I would presume the place you'd put it would be in here: https://github.com/coleifer/walrus/blob/master/walrus/models.py#L328
You'd add some hooks so that when the containerfield was updated you'd update the secondary index too if indexing was enabled. It does seem like a pretty bit task

**Comment by coleifer** [comment]
Due to the inefficiency/complexity, I think I'm going to mark this wontfix.
