### ISSUE TITLE
"Error releasing lock" if the lock expired through TTL

### ISSUE THREAD

**Issue by fernandocamargoai** [coleifer/walrus#155]
I was debugging my code and took some time inside the code that creates a lock with a context manager and after running it, I got `Error releasing lock` because it was expired. Is it the expected behavior?

**Comment by coleifer** [comment]
The reason this raises an exception is because, when that lock expires another process could acquire it while your first process is still running. Locks expire as a fail-safe to prevent a process from acquiring, then crashing without releasing lock. Your locks should only be expiring when a crash happens - if they are expiring while you're still doing work then you need to increase TTL.

**Comment by fernandocamargoai** [comment]
Okay, it makes sense, @coleifer. But could we have a custom exception for that? RuntimeError is too generic.
