### ISSUE TITLE
"lock.event:" pollution

### ISSUE THREAD

**Issue by frafra** [coleifer/walrus#172]
Even if the lock mechanism work as expected, the database is full of `lock.event:*` keys. If I run `LPOP lock.event:key` I get a `1` as reply, then `lock.event:key` disappear.

I am using the `with lock:` construct. I did various tests, but the problem still persists.

Walrus 0.9.1 (I noticed there is no GitHub release which such tag) and Redis 6.2.7.

**Comment by coleifer** [comment]
That's intended and described in the docstring for `Lock`: https://walrus.readthedocs.io/en/latest/api.html#walrus.Lock

Unlike redis-py, our implementation does not do a spin-lock. We use an "event" key (just a redis list) so that if there is contention for a lock:

* thread 1 acquires the lock by atomically setting the lock key
* thread 2 attempts to acquire the lock, but cannot set the lock key (since it was set by t1)
* thread 2 blocks by issuing a blocking list-pop on the event key (with or without a timeout)
* thread 1 finishes up, releases the lock by deleting the lock key, and trims-then-pushes a single value onto the event key
* thread 2's blocking pop now succeeds (since t1 pushed a value, which t2 popped)

If there is no contention, then yes -- when the lock is released there will be a single value in the event key.

If these keys are causing you a problem, I suggest subclassing and extending `lock_release` lua script to optionally add a TTL to those event keys, or just write your own spinlock.

**Comment by leiserfg** [comment]
>If these keys are causing you a problem, I suggest subclassing and extending lock_release lua script...

@coleifer  First of all thanks for this awesome lib. Sorry to bring this back but will you consider making that the default, maybe using the list ttl as twice an event ttl (if set in the constructor)  as a crude heuristic? I need many locks because of multitenancy and this will blow my Redis' keyspace.

**Comment by arcsun** [comment]
The problem is warlus override the lock method of redis-py, instead it should create this lock method with different name

**Comment by coleifer** [comment]
If you want to use the redis-py implementation, you can use:

```
w = Database()  # Walrus database instance.
super(Database, w).lock  # Redis.lock method.
```
