### ISSUE TITLE
Is Expiring Hashes supported in Walrus?

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [coleifer/walrus#186]
To delete a hash in redis, we can use `EXPIRE <hash> <time_in_seconds>` which will delete the hash after `time_in_seconds`

Do we have this feature included in walrus?

**Comment by coleifer** [comment]
Walrus extends the redis-py client so all the redis methods are available: https://redis-py.readthedocs.io/en/stable/commands.html#redis.commands.core.CoreCommands.expire

**Comment by sridhar562345** [comment]
@coleifer 
I am trying to expire the key as below, but getting the object has no attribute expire error
```py
from walrus import Model, TextField, DateTimeField, Database

db = Database(host="host", port="port")


class Hello(Model):
    __database__ = db

    name = TextField(primary_key=True)
    ...
    
user_drop = Hello.get(Hello.name == "some_name")
user_drop.expire(10)
```
Am I missing something or is there another way of handling it?

**Comment by coleifer** [comment]
Models are not a good fit for simple expiry since they may contain a number of values stored in indexes, but if you are not using any indexes you can:

```python
user_drop = Hello.get(...)
user_hash = user_drop.to_hash()  # Get corresponding hash.
user_hash.expire(10)  # Will expire the underlying hash, but not the data in the indexes.
```

To see what is necessary to remove from indexes, see the `Model.delete()` code in the `models.py` file. In short, models are composite data-structures are will not play well with simple expiration logic.
