### ISSUE TITLE
Handling json

### ISSUE THREAD

**Issue by waveman68** [coleifer/walrus#192]
Starting with redis 6-ish  and redis-stack in 2022 , redis introduced json as a full-fledged citizen. Currently, the only way I can access the json is through walrus Database via the superclass. This works but is somewhat suboptimal, because the IDE does not provide method information and has a warning squiggly line under all methods like this...

Is there any way to add json as a full-fledged walrus container? I'm afraid I don't have the time at the moment to dive into the details of the walrus structure to make a PR.

**Comment by coleifer** [comment]
Well, I wouldn't call it full-fledged support, if I understand correctly JSON is a redis extension module.

Additionally, Walrus is designed specifically so that any functionality in the `redis.Redis` client is available when using walrus. The Redis-py JSON client is already built-out and offers quite a large amount of functionality, I suggest you use it as it works perfectly fine:

```
>>> from walrus import Database
>>> db = Database()
>>> db.json()
<redis.commands.json.JSON at 0x7ff57cef0278>
```

**Comment by waveman68** [comment]
I get this and already implemented it this way. But IDE's flag this as an unresolved attribute and do not provide completeion. Please implement JSON as a container to resolve this. I would be happy to support if you can point me to how to implement this the walrus way.

**Comment by coleifer** [comment]
Other options than writing unnecessary code:

* get a better ide
* use the documentation instead of the ide
* write a container in your own fork
