### ISSUE TITLE
enhancement request: TimeDeltaField.

### ISSUE THREAD

**Issue by stuaxo** [coleifer/walrus#37]
Hi,
   Is there any chance of adding TimeDeltaField ?

Cheers
S

**Comment by stuaxo** [comment]
So I'm guessing this will look like this:

```python
class TimeDeltaField(_ScalarField):
    def db_value(self, value):
        seconds = value.total_seconds()
        return seconds

    def python_value(self, value):
        if isinstance(value, (basestring_type, int, float)):
            return datetime.timedelta(seconds=float(value))
        return value
```

^ Seconds is a float in db_value, or do I need to make it a string.

**Comment by stuaxo** [comment]
Work is now on branch  https://github.com/stuaxo/walrus/tree/timedelta

**Comment by coleifer** [comment]
This field, while certainly useful, is probably something that can remain in a third-party library rather than part of walrus itself. For instance, there is no walrus field type for representing python's Decimal objects either. If you end up releasing a library that has documentation and tests I will be happy to link to it in the walrus documentation, but will pass on adding this feature.

**Comment by stuaxo** [comment]
NP, I will try and put this in a repo... I guess something like redis-lite is a useful in a test strategy?
