### ISSUE TITLE
Autosuggest: storing words of other languages(UTF-8 support)

### ISSUE THREAD

**Issue by ahmadazizi** [coleifer/walrus#91]
I wasn't able to store words that are non-english. for example ac.store('سلام') is not searchable by autosuggest.
Does this library support utf-8 words?

**Comment by coleifer** [comment]
Docs are clear: https://walrus.readthedocs.io/en/latest/api.html#walrus.Autocomplete

> Autocompletion for ascii-encoded string data.

**Comment by ahmadazizi** [comment]
So the autocompletion is only for ascii-encoded strings, no support for unicode chars. Is there any technical limitation that prevents from implementing that?

**Comment by ahmadazizi** [comment]
@coleifer Is there any technical limitation behind that?

**Comment by coleifer** [comment]
Yes, so there are two options I'm aware of for making autocomplete with Redis, both utilize zsets. You can put all items into a zset with score=0 and they are sorted lexicographically (bytewise). That works for ascii but may be weird for utf8/latin1/etc. Additionally, you cannot assign any boosts or anything since scores are all zero.

What we do in walrus is utilize the score functionality by calculating a base-27 representation of the string being auto-completed, to about 10 characters. Supporting additional characters is not possible because we have to increase our exponents so large that we can't store many different characters.
